apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $fname, $contents := .Values.configFiles }}
  {{ $fname }}: |
{{ $contents | indent 4 }}
  {{- end }}