replicaCount: 2

image:
  repository: ghcr.io/hello-world-argocd-org/hello-world
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

probes:
  enabled: true
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 5

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: hello-world.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# ================ EXAMPLES OF SETTING ENV VARS ===================

# free-form key/values merged into the ConfigMap data:
config:
  CUSTOM_MESSAGE: "Hello from config"

# optional: supply whole files as config entries
configFiles: {}
#  application.yaml: |
#    server:
#      shutdown: graceful

# opt-in/override env/envFrom at container level (optional)
env: []
envFrom: []